### ISSUE TITLE
Support GitHub code archives as dat source

### ISSUE THREAD

**Issue by PhasecoreX** [emmercm/igir#1275]
### Is your feature request related to a problem?

I tried to do this:
```
npx --yes igir@latest move test clean \
    --dat "https://github.com/MetalSlug/MAMERedump/archive/refs/heads/main.zip" \
    ...
```

But Igir says:
```
ERROR: https://github.com/MetalSlug/MAMERedump/archive/refs/heads/main.zip: failed to parse file: file doesn't exist: https://github.com/MetalSlug/MAMERedump/archive/refs/heads/main.zip
```

If I go to that URL, it downloads the entire repo as a zip file, which contains a bunch of dat files and can be used with Igir as-is.

### Describe the solution you'd like

Igir should download the zip file and use it like a local zip file. The documentation says "`igir` also supports URLs to DAT files and archives." so I think this is already supported, but maybe GitHub is doing some weird redirection that Igir doesn't support?

### Additional context

I'm like 99% certain these dat files won't work until CHD/RVZ support is added anyway, but maybe there are other GitHub repo dat files out there that this could fix.

**Comment by emmercm** [comment]
I found one or two places where the temp dir wasn't being created before a file needed to use it, which may include this issue. It should be fixed when https://github.com/emmercm/igir/pull/1233 lands, which is large enough that I'm holding back doing much more to v2. I'm still testing it pretty heavily against my personal ROM collection before releasing it.

Those DATs should actually work as-is since Igir is considering CHD files to be "raw" today. If you specify `--temp-dir <path>` manually it may work fine.

**Comment by emmercm** [comment]
You can also test against v3's branch with some npx magic:

```shell
npm exec --yes -- "github:emmercm/igir#emmercm/3.0.0-feature" [commands..] [options]
```
