### ISSUE TITLE
Report on unmatched files in input directories

### ISSUE THREAD

**Issue by JaydeSix** [emmercm/igir#316]
### Describe the solution you'd like

First off thanks for such a wonderful tool, I've been looking for something like this for years.
I was wondering if it's possible to add filtering to the report, like list only missing games, or list all unknown files? Looked through and didn't see anything like that already implemented.

Thanks again.

**Comment by fooness** [comment]
_This is more of a comment than an answer to your question._

Filtering and/or sorting the `.csv` report can probably be achieved with most text processing tools. For example, you could probably open the file in e.g. LibreOffice Calc, Numbers on macOS, or Microsoft Excel and browse, filter, and sort the report in any way you like; or use CLI/GNU/UNIX commands like `grep MISSING path/to/report.csv` et cetera.

Maybe this would rather need some extensive community-maintained examples in the docs folder, instead of trying to replicate and integrating this functionality which sounds simple at first, but would be very flexible to be of real use compared to external tools that were basically created for—among others—this purpose.

**Comment by fooness** [comment]
> True, though given all the ways the files themselves can be filtered, I was curious if that could be extended to the reports without having to download another piece of software. […] Wouldn't have thought to ask if not for the call for feedback/feature requests at the bottom of the page.

Sorry if my answer was somewhat discouraging; that was not my intention! Just wanted to point out that maybe we already have great tools at hand which could, at least as long as this feature does not exist, help ourselves. :)

**Comment by JaydeSix** [comment]
> > True, though given all the ways the files themselves can be filtered, I was curious if that could be extended to the reports without having to download another piece of software. […] Wouldn't have thought to ask if not for the call for feedback/feature requests at the bottom of the page.
> 
> Sorry if my answer was somewhat discouraging; that was not my intention! Just wanted to point out that maybe we already have great tools at hand which could, at least as long as this feature does not exist in `igir`, help ourselves. :)

I didn't take it as discouraging, I appreciate the help, I hadn't considered LibreOffice and it definitely does the trick, a bit more of a learning curve then I was expecting, haven't done anything with tables and spreadsheets before, but I got there.

**Comment by emmercm** [comment]
I appreciate the feedback @JaydeSix, and I appreciate you helping out @fooness!

What you said above about using a third-party tool to do the filtering is also where my head is at, that's why I made the report format CSV. A lot of other tools have their own report format that isn't easily parseable by other programs.

---

Reporting on unknown and duplicate files is interesting. Do you have an example of an existing tool and how they handle this, or do you have an idea of how you would want them reported on? `igir` started out being so DAT-focused that I didn't consider other cases like this.

**Comment by JaydeSix** [comment]
> Reporting on unknown and duplicate files is interesting. Do you have an example of an existing tool and how they handle this, or do you have an idea of how you would want them reported on? `igir` started out being so DAT-focused that I didn't consider other cases like this.

Thanks for taking the time to look into this. Never really found a good tool to handle this, I use my own naming conventions, many programs start with a name check so I have had to use a tool to rename a copy of the folder back to no-intro or redump standard and then compare to the dat, and then use a script to hash compare the files in the folder themselves and spit out a list of unique files. 

So many extra steps involved. As far as what I'd like to see in igir, it would be great if it would report unknown files just like it does with found and missing, just status unknown. Duplicates is less important and would benefit most if it displayed path name with it.

Maybe the use cases are already covered by functions in igir though, so just to check both of these would help towards trying to fix/update an existing folder rather than move/copy to a new folder (helpful for people like me who organize/name their files differently). Unknown file reporting would list files that were not supposed to be there including stuff like bad dumps that were removed from the dat when a good dump was found. A person might have altered or have additional files not in the dat they would want kept though so clean wouldn't help for that. Duplicates would be helpful to weed out misnamed or miscopied files that might exist in multiple places but I'm not sure there is a clean way to deliver that information.

**Comment by emmercm** [comment]
@JaydeSix for the ROM naming, I'd be interested in understanding why you prefer a custom naming scheme over the DAT group naming - maybe there's something that I can add there? Maybe `{inputBasename}`?

---

The unmatched files addition would be good, I can definitely work on that.

**Comment by JaydeSix** [comment]
Awesome, thanks for adding that. As far as the naming goes, I'm not asking for any changes there, you're program works perfect for me in that regard since I use it strictly for reporting. The reason I change the naming though is I used to use the Analogue Mini Nt (before I got a MiSTer) and it had a weird system quirk where there was a limit on filename characters, when all the rom folders were added up if it exceeded it, then chunks of games wouldn't display. So I got use to removing any redundancy I could so /system/proto/game (proto).rom would lose it's suffix since it's already in a folder labeling what it is. Same for countries, alts, etc.
