### ISSUE TITLE
Add --miss-only to report command

### ISSUE THREAD

**Issue by graphixillusion** [emmercm/igir#346]
### Is your feature request related to a problem?

Quickly generate a miss list of missing roms

### Describe the solution you'd like

It would be comfortable to have an option to generate just a list of which roms are missing in the set. Something like "--miss-only" flag specific for the report command.

### Additional context

Thank your for this great app!

**Comment by emmercm** [comment]
Thank you @graphixillusion!

I owe a docs page on reporting, this request is similar to https://github.com/emmercm/igir/issues/316 and I think an explanation of current functionality plus intended use would be good.

I'm hesitant to add too many CLI flags because it makes the help message (and therefore README) longer and more overwhelming. `igir` already has more options than most programs, so it's already potentially out of reach for casual users. For this request, you would be able to filter the CSV that's already output to `Status="MISSING"` using Excel, Numbers, or some other free app such as LibreOffice Calc.

**Comment by graphixillusion** [comment]
@emmercm Yeah nice! I think it's very clear and well written!

**Comment by emmercm** [comment]
That's great news, thank you!

**Comment by graphixillusion** [comment]
Hey @emmercm, i was thinking: what about the ability to create a fixdat of the missing sets? This is a very common and used option in this world, i think it's worth to consider as an option to add.

**Comment by graphixillusion** [comment]
@emmercm it's ok, don't worry. Basically any rom manager has this option: the two most used are clrmame and Romvault
