### ISSUE TITLE
Thumbnail support

### ISSUE THREAD

**Issue by lostb1t** [emmercm/igir#483]
### Is your feature request related to a problem?

Great project. Maybe adding thumbnail/artwork support would be a nice addition? (Loaded from https://github.com/libretro-thumbnails/libretro-thumbnails)

### Describe the solution you'd like

.

**Comment by emmercm** [comment]
Hi @sarendsen, I'm confused what about artwork `igir` could help with. I haven't come across DATs of artwork before, and I haven't seen complicated file sorting requirements before.

Can you describe the end goal you would want?

**Comment by 21millStreets** [comment]
I have to try with Miyoo, but I like this idea to take Thumbnails related with the DAT you want into your collection.

**Comment by emmercm** [comment]
@sarendsen to clarify, is the idea to do something like:

```shell
igir \
  --input libretro-thumbnails/ \
  --output some/thumbnail/dir \
  --dir-dat-name \
  --match-files-by-game-name
```

where a file of the name `Alien 3 (USA, Europe).*` (`.png` in this case) would match to the game name `Alien 3 (USA, Europe)`, and then be written to `some/thumbnail/dir/Nintendo - Game Boy/Alien 3 (USA, Europe).png`?

---

There are other ROM managers that support matching by filename rather than checksum (I assume to better enable CHD, CSO/ZSO, GCZ/RVZ, and the like), and it has been on my idea list for some time now, but I hadn't yet found a compelling reason to implement it. Maybe this is it.
