### ISSUE TITLE
clearer information on 1g1r roms status

### ISSUE THREAD

**Issue by feurry** [emmercm/igir#654]
### Is your feature request related to a problem?

With the following roms in the source dir
Alien 3 (Europe).zip
Alien 3 (USA).zip

--single --prefer-region EUR,USA
in the report under the 'game name' and 'status'
Alien 3 (Europe)	FOUND
Alien 3 (USA)	MISSING

with
--prefer-region USA,EUR
Alien 3 (Europe)	MISSING
Alien 3 (USA)	FOUND

I am not "missing" the USA or EUR version in either case. The --single option is enabled so it is being skipped.

In the 'Rom Files' column the secondary rom itself is listed with status UNMATCHED in the report. The rom has been matched to the dat file and is valid so that's a bit misleading. It was purposely ommited or unneeded due to the --single and region settings.

### Describe the solution you'd like

The rom name could be marked "SKIPPING" or "1g1r SKIP" or something other than "MISSING" to indicate that it exists, but was skipped or disabled by --single.

The Rom File could be marked something other than "UNMATCHED" to indicate that it exists and is valid but is disabled by --single. Maybe "OMMITED" or "UNNEEDED".

**Comment by emmercm** [comment]
I agree this is confusing behavior with `--single`. I tried to fix something similar in https://github.com/emmercm/igir/pull/532 but clearly, it isn't working right. I'll have to dig in on this.

**Comment by emmercm** [comment]
@feurry can you try the testing instructions in https://github.com/emmercm/igir/pull/667 on your local machine? I'm trying to change the reporting behavior so that:

- When not 1G1R, always report on every game (every parent and every clone)
- When 1G1R, for each parent:
  - If any clone is found: report that one clone as FOUND and don't report on any others
  - If no clone is found: report every clone as MISSING

---

Separately, I think I want to rename UNMATCHED to UNUSED to better convey meaning. It's supposed to represent input files that weren't used as the source for any output file.

**Comment by feurry** [comment]
npm exec --yes -- "github:emmercm/igir#emmercm/report-exclude-non-preferred" copy zip clean report -d *.dat -i nesSource/ -o nesOut/ --no-bios --only-retail --single --prefer-language EN --prefer-region EUR,USA,WORLD -vvv

The report shows the 2nd rom as 'UNMATCHED'
Alien 3 (Europe),FOUND
UNMATCHED,nesSource/Roms/Alien 3 (USA).zip

I think marking 1 clone FOUND if any are found will be just as confusing as not marking any. My thinking is that if a clone is found it is marked as such so I don't spend time trying to confirm if I'm actually missing it or it was skipped on purpose.

I guess the end goal with 1g1r is to be able to find out what files I'd be missing to complete a 1g1r set, not the entire collection. Either the fixdat or the reporting should be clear to help achieve that. 

So hopefully the FOUND and UNUSED will be enough to figure that out.

**Comment by feurry** [comment]
OK I just realized that the order of the report matters. It makes a lot more sense now!

✓ Nintendo - Nintendo Entertainm | 790/2,002 retail releases written

The first 2002 rows of the report show FOUND or MISSING, and that's everything to complete the 1g1r. Everything below that row marked UNMATCHED is not needed for a 1g1r set.

I guess you can ignore marking the clones, and I agree UNUSED is better wording.

Thanks for your hard work! It's a very fast scanner.

**Comment by emmercm** [comment]
@feurry instead of omitting clones from the CSV report that weren't preferred, would a new status of "SKIPPED" (or maybe "IGNORED") be more clear? As in, because one of the clones was "FOUND" the others won't be written. I'm very open to suggestions on the wording if there's a synonym to "SKIPPED" you like better.

---

And yeah, "UNMATCHED" is unrelated, those are input files that weren't used for any reason, either because it's a duplicate input file or because that clone wasn't preferred. It's to help people better debug why something may not have been written to the output. "UNMATCHED" is probably bad because it implies that the file doesn't exist in any DAT.

**Comment by emmercm** [comment]
@feurry thank you for the praise! I'm actually a little surprised to hear you think it's fast, my choice in Node.js probably limits how fast this can be. It's just what I know best 🙂.

**Comment by emmercm** [comment]
I'm going to go with the word "IGNORED", and I'll write it into the https://igir.io/output/reporting/ docs.
